# Generated by Django 3.0 on 2020-05-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_photo', models.ImageField(blank=True, null=True, upload_to='about/%Y')),
                ('about_photo_name', models.CharField(blank=True, error_messages={'unique': 'Another profile photo with this name already exists.'}, max_length=200, null=True, unique=True)),
                ('about_text', models.TextField(blank=True, null=True)),
                ('current_photo', models.CharField(choices=[('disabled', 'disabled'), ('enabled', 'enabled')], default='disabled', error_messages={'unique': 'Another artwork already uses this hero position.'}, max_length=8)),
                ('uploaddate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('art', models.ImageField(upload_to='artworks/%Y')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('hero', models.CharField(blank=True, choices=[('left', 'left'), ('middle', 'middle'), ('right', 'right')], error_messages={'unique': 'Another artwork already uses this hero position.'}, max_length=6, null=True, unique=True)),
            ],
        ),
    ]
