# Generated by Django 3.0 on 2020-05-03 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='current_photo',
        ),
    ]
