# Generated by Django 3.0 on 2020-05-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='views',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
