# Generated by Django 3.0 on 2020-04-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200430_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='hero',
            field=models.IntegerField(blank=True, choices=[(1, 'left'), (2, 'center'), (3, 'right')], error_messages={'unique': 'Another artwork already uses this hero position.'}, null=True, unique=True),
        ),
    ]
