# Generated by Django 3.0 on 2020-05-10 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200510_0744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='views',
        ),
    ]
