# Generated by Django 3.0 on 2020-05-03 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_about_current_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='about_photo_name',
        ),
        migrations.RemoveField(
            model_name='about',
            name='current_photo',
        ),
    ]
