# Generated by Django 3.0 on 2020-05-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_artwork_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=160, null=True),
        ),
    ]
