# Generated by Django 3.0 on 2020-06-24 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20200526_2101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
