# Generated by Django 3.0 on 2020-06-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_delete_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='date',
            new_name='created_dt',
        ),
        migrations.AddField(
            model_name='artwork',
            name='updated_dt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
