# Generated by Django 3.0 on 2020-05-04 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20200504_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='uploaddate',
            new_name='date',
        ),
    ]
