# Generated by Django 3.0 on 2020-05-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20200504_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='log',
            field=models.TextField(blank=True, null=True),
        ),
    ]
