# Generated by Django 3.0 on 2020-05-06 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_message_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='log',
        ),
    ]
