# Generated by Django 3.0 on 2020-05-06 07:50

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_remove_message_log'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='message',
            managers=[
                ('slackalert', django.db.models.manager.Manager()),
            ],
        ),
    ]
