# Generated by Django 3.0 on 2020-05-06 18:16

from django.db import migrations, models
import django.db.models.deletion
import slack.web.client


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20200506_0750'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackAlert',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='portfolio.Message')),
            ],
            bases=('portfolio.message', slack.web.client.WebClient),
        ),
        migrations.AlterModelManagers(
            name='message',
            managers=[
            ],
        ),
    ]
