# Generated by Django 3.0 on 2020-05-07 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_auto_20200507_2058'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactSuccessView',
        ),
    ]
